# Generated by Django 4.1.7 on 2023-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=40)),
            ],
        ),
    ]
