# Generated by Django 4.1.7 on 2023-05-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FodaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortalaza', models.CharField(max_length=60)),
                ('oportunidad', models.CharField(max_length=60)),
                ('debilidad', models.CharField(max_length=60)),
                ('amenaza', models.CharField(max_length=60)),
            ],
        ),
    ]
