# Generated by Django 4.1.7 on 2023-05-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fodapersonal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fodapersonal',
            old_name='fortalaza',
            new_name='fortaleza',
        ),
    ]
