# Generated by Django 4.1.7 on 2023-05-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fortalaza_fodapersonal_fortaleza'),
    ]

    operations = [
        migrations.AddField(
            model_name='fodapersonal',
            name='miembro',
            field=models.CharField(default='hola', max_length=60),
            preserve_default=False,
        ),
    ]
